<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>zftp</AssemblyName>
    <RootNamespace>ZFTP.Cli</RootNamespace>
    <Version>2.7.9</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZFTP.Portable\ZFTP.Portable.csproj" />
  </ItemGroup>
</Project>
